import { Inter } from 'next/font/google'
import './globals.css'
import AppProvider from '@/Components/AppContext'
import { AccountProvider } from '@/app/Context/Account';
import { SocketProvider } from '@/app/Context/Socket';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AppProvider>
        <AccountProvider>
        <SocketProvider>

        {children}
    
          </SocketProvider>      
        </AccountProvider>
        </AppProvider>

        </body>
    </html>
  )
}
